import enMessages from '../../../messages/en.json';
import arMessages from '../../../messages/ar.json';

const translationMap: Record<string, string> = {};

function isRecord(val: unknown): val is Record<string, unknown> {
  return typeof val === 'object' && val !== null;
}

function buildTranslationMap(arObj: unknown, enObj: unknown) {
  if (!isRecord(arObj) || !isRecord(enObj)) return;
  for (const key of Object.keys(arObj)) {
    const arVal = arObj[key];
    const enVal = enObj[key];
    if (typeof arVal === 'string' && typeof enVal === 'string') {
      translationMap[arVal.trim()] = enVal.trim();
    } else if (isRecord(arVal) && isRecord(enVal)) {
      buildTranslationMap(arVal, enVal);
    }
  }
}

// Build the translation mapping from the localization bundles
buildTranslationMap(arMessages, enMessages);

// Manual fallbacks for common report metadata and terms
const customTranslations: Record<string, string> = {
  'نعم': 'Yes',
  'لا': 'No',
  'المخزون المتوفر': 'Available Inventory',
  'الكمية المحجوزة': 'Reserved Qty',
  'الكمية المتوفرة': 'Available Qty',
  'المخزن المتوفر': 'Available Inventory',
  'تاريخ التقرير': 'Report Date',
  'الرقم الضريبي': 'Tax Number',
  'سجل تجاري': 'CR',
  'هاتف': 'Phone',
  'بريد': 'Email',
  'تم الإنشاء بواسطة': 'Generated by',
  'النطاق': 'Scope',
  'بيان جرد - Stocktake Manifest': 'STOCKTAKE MANIFEST',
  'بيان جرد - STOCKTAKE MANIFEST': 'STOCKTAKE MANIFEST',
  'أمر شراء - Purchase Order': 'PURCHASE ORDER',
  'سند تحويل مخزني - Stock Transfer': 'STOCK TRANSFER',
  'سند استلام بضاعة - Goods Receipt': 'GOODS RECEIPT',
  'تسوية مخزنية - Inventory Adjustment': 'INVENTORY ADJUSTMENT',
};

export function translateToEnglish(text: string): string {
  if (!text) return '';
  const trimmed = text.trim();

  // 1. Direct match in recursive translation map
  if (translationMap[trimmed]) {
    return translationMap[trimmed];
  }

  // 2. Direct match in custom overrides
  if (customTranslations[trimmed]) {
    return customTranslations[trimmed];
  }

  // 3. Match and translate dynamic compound strings
  if (trimmed.startsWith('تاريخ التقرير:')) {
    return trimmed.replace('تاريخ التقرير:', 'Report Date:');
  }
  if (trimmed.startsWith('الرقم الضريبي:')) {
    return trimmed.replace('الرقم الضريبي:', 'Tax Number:');
  }
  if (trimmed.startsWith('سجل تجاري:')) {
    return trimmed.replace('سجل تجاري:', 'CR:');
  }
  if (trimmed.includes('هاتف:') || trimmed.includes('بريد:')) {
    return trimmed
      .replace(/هاتف:/g, 'Phone:')
      .replace(/بريد:/g, 'Email:');
  }
  if (trimmed.startsWith('تم الإنشاء بواسطة:')) {
    return trimmed.replace('تم الإنشاء بواسطة:', 'Generated by:');
  }
  if (trimmed.startsWith('النطاق:')) {
    return trimmed.replace('النطاق:', 'Scope:');
  }
  
  const pageMatch = trimmed.match(/صفحة\s+(\d+)\s+من\s+(\d+)/);
  if (pageMatch) {
    return `Page ${pageMatch[1]} of ${pageMatch[2]}`;
  }

  return text;
}
