
import { 
  PR_STATUS, 
  PO_STATUS, 
  GRN_STATUS, 
  STOCKTAKE_STATUS, 
  ISSUE_STATUS, 
  TRANSFER_STATUS, 
  ADJUSTMENT_STATUS,
  KITCHEN_REQUEST_STATUS
} from '@logirest/shared-types';

import { 
  PurchaseRequest, PurchaseOrder, GRN, 
  StockIssue, Transfer, Adjustment 
} from '@/types/documents';
import { StocktakeSession } from '@/features/operations/types/stocktake';
import { KitchenRequestDetail } from '@/features/operations/types/kitchen-request';

/**
 * Mock Factory for Domain Documents
 * Ensures mock data consistently follows Zod schemas and centralized statuses.
 */

const mockBaseDocument = (type: string, overrides: Record<string, unknown> = {}) => ({
  id: Math.random().toString(36).substring(7),
  documentNumber: `${type}-${Math.floor(1000 + Math.random() * 9000)}`,
  type,
  warehouseId: 'WH-001',
  branchId: 'BR-001',
  notes: 'Mock document generated by factory',
  createdBy: 'Culinary Admin',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  postedAt: null,
  postedBy: null,
  version: 1,
  ...overrides
});

export const MockFactory = {
  createPR: (overrides: Partial<PurchaseRequest> = {}): PurchaseRequest => mockBaseDocument('PR', {
    status: PR_STATUS.DRAFT,
    requestedByDept: 'Kitchen-Main',
    requiredByDate: new Date(Date.now() + 86400000).toISOString(),
    lines: [],
    ...overrides
  }) as PurchaseRequest,

  createPO: (overrides: Partial<PurchaseOrder> = {}): PurchaseOrder => mockBaseDocument('PO', {
    status: PO_STATUS.DRAFT,
    pr_id: null,
    supplierId: 'SUP-001',
    currency_id: 'SAR',
    expected_deliveryDate: new Date(Date.now() + 172800000).toISOString(),
    lines: [],
    ...overrides
  }) as PurchaseOrder,

  createGRN: (overrides: Partial<GRN> = {}): GRN => mockBaseDocument('GRN', {
    status: GRN_STATUS.DRAFT,
    po_id: null,
    supplierId: 'SUP-001',
    currency_id: 'SAR',
    fx_rate: 1.0,
    fx_rate_captured_at: new Date().toISOString(),
    lines: [],
    ...overrides
  }) as GRN,

  createStocktakeSession: (overrides: Partial<StocktakeSession> = {}): StocktakeSession => {
    const base = mockBaseDocument('STOCKTAKE', overrides);
    return {
      ...base,
      sessionNumber: (overrides as Record<string, unknown>).sessionNumber as string || base.documentNumber,
      sessionName: overrides.sessionName || 'Monthly Inventory',
      snapshotAt: overrides.snapshotAt || new Date().toISOString(),
      startedBy: overrides.startedBy || 'Culinary Admin',
      status: overrides.status || STOCKTAKE_STATUS.DRAFT,
      warehouseName: overrides.warehouseName || 'Main Warehouse',
      items: overrides.items || [],
      version: overrides.version || 1,
      ...overrides
    } as unknown as StocktakeSession;
  },

  createIssue: (overrides: Partial<StockIssue> = {}): StockIssue => mockBaseDocument('ISSUE', {
    status: ISSUE_STATUS.DRAFT,
    destinationDeptId: 'Production-Line',
    requestedBy: 'Chef de Cuisine',
    lines: [],
    ...overrides
  }) as StockIssue,

  createTransfer: (overrides: Partial<Transfer> = {}): Transfer => mockBaseDocument('TRANSFER', {
    transferStatus: TRANSFER_STATUS.DRAFT,
    status: TRANSFER_STATUS.DRAFT,
    from_warehouseId: 'WH-001',
    to_warehouseId: 'WH-002',
    shippedAt: null,
    receivedAt: null,
    lines: [],
    ...overrides
  }) as Transfer,

  createAdjustment: (overrides: Partial<Adjustment> = {}): Adjustment => mockBaseDocument('ADJUSTMENT', {
    status: ADJUSTMENT_STATUS.DRAFT,
    reason: 'DAMAGE',
    approved_by: null,
    lines: [],
    ...overrides
  }) as Adjustment,

  createKitchenRequest: (overrides: Partial<KitchenRequestDetail> = {}): KitchenRequestDetail => {
    const base = mockBaseDocument('KITCHEN_REQUEST', overrides);
    return {
      ...base,
      request_number: (overrides as Record<string, unknown>).request_number as string || base.documentNumber,
      status: overrides.status || KITCHEN_REQUEST_STATUS.DRAFT,
      departmentId: overrides.departmentId || 'DEPT-001',
      requestedBy: overrides.requestedBy || 'Barakat Amin',
      requested_at: base.createdAt,
      updatedAt: base.createdAt,
      items: overrides.items || [],
      ...overrides
    } as unknown as KitchenRequestDetail;
  },

  createList: <T>(factory: (overrides: Partial<T>) => T, count: number, overrides: Partial<T> = {}): T[] => {
    return Array.from({ length: count }, (_, i) => {
      const itemOverrides: Record<string, unknown> = { 
        id: `ID-${i + 1}`, 
        ...overrides 
      };
      
      // Handle different numbering fields based on document type
      // We can't easily know the type here, so we add all common ones
      // and let the factory pick what it needs.
      itemOverrides.documentNumber = `DOC-${i + 1}`;
      itemOverrides.sessionNumber = `SES-${i + 1}`;
      itemOverrides.request_number = `REQ-${i + 1}`;
      
      return factory(itemOverrides as Partial<T>);
    });
  },

  wrapPagination: <T>(data: T[], page = 1, pageSize = 10) => ({
    data,
    meta: {
      page,
      pageSize,
      total: data.length,
      totalPages: Math.ceil(data.length / pageSize),
    }
  })
};
