
import { 
  PR_STATUS, 
  PO_STATUS, 
  GRN_STATUS, 
  STOCKTAKE_STATUS, 
  ISSUE_STATUS, 
  TRANSFER_STATUS, 
  ADJUSTMENT_STATUS,
  KITCHEN_REQUEST_STATUS
} from '@/contracts/statuses';

import { 
  PurchaseRequest, PurchaseOrder, GRN, 
  StockIssue, Transfer, Adjustment 
} from '@/types/documents';
import { StocktakeSession } from '@/features/operations/types/stocktake';
import { KitchenRequestDetail } from '@/features/operations/types/kitchen-request';

/**
 * Mock Factory for Domain Documents
 * Ensures mock data consistently follows Zod schemas and centralized statuses.
 */

const mockBaseDocument = (type: string, overrides: Record<string, unknown> = {}) => ({
  id: Math.random().toString(36).substring(7),
  document_number: `${type}-${Math.floor(1000 + Math.random() * 9000)}`,
  type,
  warehouse_id: 'WH-001',
  branch_id: 'BR-001',
  notes: 'Mock document generated by factory',
  created_by: 'Culinary Admin',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  posted_at: null,
  posted_by: null,
  version: 1,
  ...overrides
});

export const MockFactory = {
  createPR: (overrides: Partial<PurchaseRequest> = {}): PurchaseRequest => mockBaseDocument('PR', {
    status: PR_STATUS.DRAFT,
    requested_by_dept: 'Kitchen-Main',
    required_by_date: new Date(Date.now() + 86400000).toISOString(),
    lines: [],
    ...overrides
  }) as PurchaseRequest,

  createPO: (overrides: Partial<PurchaseOrder> = {}): PurchaseOrder => mockBaseDocument('PO', {
    status: PO_STATUS.DRAFT,
    pr_id: null,
    supplier_id: 'SUP-001',
    currency_id: 'SAR',
    expected_delivery_date: new Date(Date.now() + 172800000).toISOString(),
    lines: [],
    ...overrides
  }) as PurchaseOrder,

  createGRN: (overrides: Partial<GRN> = {}): GRN => mockBaseDocument('GRN', {
    status: GRN_STATUS.DRAFT,
    po_id: null,
    supplier_id: 'SUP-001',
    currency_id: 'SAR',
    fx_rate: 1.0,
    fx_rate_captured_at: new Date().toISOString(),
    lines: [],
    ...overrides
  }) as GRN,

  createStocktakeSession: (overrides: Partial<StocktakeSession> = {}): StocktakeSession => {
    const base = mockBaseDocument('STOCKTAKE', overrides);
    return {
      ...base,
      session_number: (overrides as Record<string, unknown>).session_number as string || base.document_number,
      session_name: overrides.session_name || 'Monthly Inventory',
      snapshot_at: overrides.snapshot_at || new Date().toISOString(),
      started_by: overrides.started_by || 'Culinary Admin',
      status: overrides.status || STOCKTAKE_STATUS.DRAFT,
      warehouse_name: overrides.warehouse_name || 'Main Warehouse',
      items: overrides.items || [],
      version: overrides.version || 1,
      ...overrides
    } as unknown as StocktakeSession;
  },

  createIssue: (overrides: Partial<StockIssue> = {}): StockIssue => mockBaseDocument('ISSUE', {
    status: ISSUE_STATUS.DRAFT,
    destination_dept_id: 'Production-Line',
    requested_by: 'Chef de Cuisine',
    lines: [],
    ...overrides
  }) as StockIssue,

  createTransfer: (overrides: Partial<Transfer> = {}): Transfer => mockBaseDocument('TRANSFER', {
    transfer_status: TRANSFER_STATUS.DRAFT,
    status: TRANSFER_STATUS.DRAFT,
    from_warehouse_id: 'WH-001',
    to_warehouse_id: 'WH-002',
    shipped_at: null,
    received_at: null,
    lines: [],
    ...overrides
  }) as Transfer,

  createAdjustment: (overrides: Partial<Adjustment> = {}): Adjustment => mockBaseDocument('ADJUSTMENT', {
    status: ADJUSTMENT_STATUS.DRAFT,
    reason: 'DAMAGE',
    approved_by: null,
    lines: [],
    ...overrides
  }) as Adjustment,

  createKitchenRequest: (overrides: Partial<KitchenRequestDetail> = {}): KitchenRequestDetail => {
    const base = mockBaseDocument('KITCHEN_REQUEST', overrides);
    return {
      ...base,
      request_number: (overrides as Record<string, unknown>).request_number as string || base.document_number,
      status: overrides.status || KITCHEN_REQUEST_STATUS.DRAFT,
      department_id: overrides.department_id || 'DEPT-001',
      requested_by: overrides.requested_by || 'Ahmed Ali',
      requested_at: base.created_at,
      updated_at: base.created_at,
      items: overrides.items || [],
      ...overrides
    } as unknown as KitchenRequestDetail;
  },

  createList: <T>(factory: (overrides: Partial<T>) => T, count: number, overrides: Partial<T> = {}): T[] => {
    return Array.from({ length: count }, (_, i) => {
      const itemOverrides: Record<string, unknown> = { 
        id: `ID-${i + 1}`, 
        ...overrides 
      };
      
      // Handle different numbering fields based on document type
      // We can't easily know the type here, so we add all common ones
      // and let the factory pick what it needs.
      itemOverrides.document_number = `DOC-${i + 1}`;
      itemOverrides.session_number = `SES-${i + 1}`;
      itemOverrides.request_number = `REQ-${i + 1}`;
      
      return factory(itemOverrides as Partial<T>);
    });
  },

  wrapPagination: <T>(data: T[], page = 1, pageSize = 10) => ({
    data,
    meta: {
      page,
      page_size: pageSize,
      total: data.length,
      total_pages: Math.ceil(data.length / pageSize),
    }
  })
};
