"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ALL_STATUSES = exports.ALL_KITCHEN_REQUEST_STATUSES = exports.KITCHEN_REQUEST_STATUS = exports.ALL_ADJUSTMENT_STATUSES = exports.ADJUSTMENT_STATUS = exports.ALL_ISSUE_STATUSES = exports.ISSUE_STATUS = exports.ALL_TRANSFER_STATUSES = exports.TRANSFER_STATUS = exports.ALL_STOCKTAKE_STATUSES = exports.STOCKTAKE_STATUS = exports.ALL_GRN_STATUSES = exports.GRN_STATUS = exports.ALL_PO_STATUSES = exports.PO_STATUS = exports.ALL_PR_STATUSES = exports.PR_STATUS = void 0;
exports.assertNever = assertNever;
exports.PR_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
    FULFILLED: 'FULFILLED',
};
exports.ALL_PR_STATUSES = ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'FULFILLED'];
exports.PO_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
    PARTIAL: 'PARTIAL',
    FULFILLED: 'FULFILLED',
};
exports.ALL_PO_STATUSES = ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'PARTIAL', 'FULFILLED'];
exports.GRN_STATUS = {
    DRAFT: 'DRAFT',
    RECEIVED: 'RECEIVED',
    POSTED: 'POSTED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
};
exports.ALL_GRN_STATUSES = ['DRAFT', 'RECEIVED', 'POSTED', 'CANCELLED', 'VOIDED'];
exports.STOCKTAKE_STATUS = {
    DRAFT: 'DRAFT',
    STARTED: 'STARTED',
    COUNTING: 'COUNTING',
    REVIEW: 'REVIEW',
    APPROVED: 'APPROVED',
    POSTED: 'POSTED',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
};
exports.ALL_STOCKTAKE_STATUSES = ['DRAFT', 'STARTED', 'COUNTING', 'REVIEW', 'APPROVED', 'POSTED', 'CLOSED', 'CANCELLED', 'VOIDED'];
exports.TRANSFER_STATUS = {
    DRAFT: 'DRAFT',
    IN_TRANSIT: 'IN_TRANSIT',
    RECEIVED: 'RECEIVED',
    POSTED: 'POSTED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
};
exports.ALL_TRANSFER_STATUSES = ['DRAFT', 'IN_TRANSIT', 'RECEIVED', 'POSTED', 'CANCELLED', 'VOIDED'];
exports.ISSUE_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    POSTED: 'POSTED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
};
exports.ALL_ISSUE_STATUSES = ['DRAFT', 'SUBMITTED', 'POSTED', 'CANCELLED', 'VOIDED'];
exports.ADJUSTMENT_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    POSTED: 'POSTED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
};
exports.ALL_ADJUSTMENT_STATUSES = ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', 'VOIDED'];
exports.KITCHEN_REQUEST_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    FULFILLED: 'FULFILLED',
    CANCELLED: 'CANCELLED',
    VOIDED: 'VOIDED',
};
exports.ALL_KITCHEN_REQUEST_STATUSES = ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'FULFILLED', 'CANCELLED', 'VOIDED'];
exports.ALL_STATUSES = [
    'DRAFT',
    'SUBMITTED',
    'APPROVED',
    'REJECTED',
    'POSTED',
    'CANCELLED',
    'RECEIVED',
    'FULFILLED',
    'PARTIAL',
    'STARTED',
    'COUNTING',
    'IN_TRANSIT',
    'OPEN',
    'VOIDED',
    'REVIEW',
    'CLOSED',
    'VARIANCE_SUBMITTED',
    'COUNTING_COMPLETED',
    'ACTIVE',
    'INACTIVE',
];
function assertNever(x) {
    throw new Error(`Unexpected status: ${x}`);
}
//# sourceMappingURL=statuses.js.map