import { z } from 'zod';
export type DocumentStatus = 'DRAFT'|'SUBMITTED'|'APPROVED'|'REJECTED'|'POSTED'|'CANCELLED';
export type DocumentType = 'GRN'|'ISSUE'|'TRANSFER'|'ADJUSTMENT'|'PR'|'PO';
export interface BaseDocument { id: string; document_number: string; type: DocumentType; status: DocumentStatus; warehouse_id: string; branch_id: string; notes: string | null; created_by: string; created_at: string; posted_at: string | null; posted_by: string | null; }
export interface LotAllocation { lot_id: string; lot_number: string; expiry_date: string | null; allocated_qty: number; override_reason: string | null; }
export interface GRN extends BaseDocument { type: 'GRN'; po_id: string | null; supplier_id: string; currency_id: string; fx_rate: number | null; fx_rate_captured_at: string | null; lines: GRNLineItem[]; }
export interface GRNLineItem { id: string; document_id: string; item_id: string; item: { id: string; code: string; name_ar: string; name_en: string; primary_uom: { id: string; code: string; name_ar: string; name_en: string; } }; lot_id: string | null; lot: { id: string; lot_number: string; expiry_date: string | null; is_expired: boolean; } | null; qty: number; uom_id: string; unit_cost: number | null; po_qty: number | null; received_qty: number; unit_cost_foreign: number; unit_cost_base: number; }
export interface PurchaseRequest extends BaseDocument { type: 'PR'; requested_by_dept: string; required_by_date: string; lines: PRLineItem[]; }
export interface PRLineItem { id: string; document_id: string; item_id: string; item: { id: string; code: string; name_ar: string; name_en: string; primary_uom: { id: string; code: string; name_ar: string; name_en: string; } }; lot_id: string | null; lot: null; qty: number; uom_id: string; unit_cost: null; requested_qty: number; approved_qty: number | null; }
export interface PurchaseOrder extends BaseDocument { type: 'PO'; pr_id: string | null; supplier_id: string; currency_id: string; expected_delivery_date: string; lines: POLineItem[]; }
export interface POLineItem { id: string; document_id: string; item_id: string; item: { id: string; code: string; name_ar: string; name_en: string; primary_uom: { id: string; code: string; name_ar: string; name_en: string; } }; lot_id: string | null; lot: null; qty: number; uom_id: string; unit_cost: number | null; ordered_qty: number; unit_price: number; total_price: number; }
export interface StockIssue extends BaseDocument { type: 'ISSUE'; destination_dept_id: string; requested_by: string; lines: IssueLineItem[]; }
export interface IssueLineItem { id: string; document_id: string; item_id: string; item: { id: string; code: string; name_ar: string; name_en: string; primary_uom: { id: string; code: string; name_ar: string; name_en: string; } }; lot_id: string | null; lot: { id: string; lot_number: string; expiry_date: string | null; is_expired: boolean; } | null; qty: number; uom_id: string; unit_cost: number | null; requested_qty: number; issued_qty: number; lot_allocations: LotAllocation[]; }
export interface Transfer extends BaseDocument { type: 'TRANSFER'; from_warehouse_id: string; to_warehouse_id: string; transfer_status: 'DRAFT'|'IN_TRANSIT'|'RECEIVED'|'POSTED'; shipped_at: string | null; received_at: string | null; lines: TransferLineItem[]; }
export interface TransferLineItem { id: string; document_id: string; item_id: string; item: { id: string; code: string; name_ar: string; name_en: string; primary_uom: { id: string; code: string; name_ar: string; name_en: string; } }; lot_id: string | null; lot: null; qty: number; uom_id: string; unit_cost: null; shipped_qty: number; received_qty: number | null; }
export type AdjustmentReason = 'DAMAGE'|'EXPIRY'|'THEFT'|'COUNTING_ERROR'|'OTHER';
export interface Adjustment extends BaseDocument { type: 'ADJUSTMENT'; reason: AdjustmentReason; approved_by: string | null; lines: AdjustmentLineItem[]; }
export interface AdjustmentLineItem { id: string; document_id: string; item_id: string; item: { id: string; code: string; name_ar: string; name_en: string; primary_uom: { id: string; code: string; name_ar: string; name_en: string; } }; lot_id: string | null; lot: null; qty: number; uom_id: string; unit_cost: null; direction: 'INCREASE'|'DECREASE'; qty_before: number; qty_adjusted: number; reason_notes: string; }
